### PR TITLE
dev

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit f997fdd has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit f997fdd with merge f997fdd...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/nrf51822/builds/195251345)
Approved by: japaric
Pushing f997fdda37a647206aac421caa21ae4273859b8d to master...

**Pull request merged**
