### PR TITLE
use stable cortex-m-semihosting API

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 5d90b5d has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 5d90b5d with merge 5d90b5d...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/nrf51822/builds/194342914)
Approved by: japaric
Pushing 5d90b5d77cd40f4a5487432e059c5e2e902c66ea to master...

**Pull request merged**
