### PR TITLE
opt-out semihosting Cargo feature

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit f39edd8 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit f39edd8 with merge f39edd8...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 78b95c8 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 78b95c8 with merge 78b95c8...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/nrf51822/builds/194338566)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 4a8e111 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 4a8e111 with merge 4a8e111...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/nrf51822/builds/194339171)
Approved by: japaric
Pushing 4a8e111af02731dcc193e9569589b6ef8e0c27ea to master...

**Pull request merged**
